# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


language: r
warnings_are_errors: true
sudo: false
cache: packages

r_github_packages:
  - r-lib/covr
  - adw96/breakaway

after_success:
  - Rscript -e 'covr::codecov()'

bioc_packages:
  - phyloseq

env:
  - R_KEEP_PKG_SOURCE=yes
  - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
  - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
