fluidPage(
  
  titlePanel("Comparison of methods for testing differences in alpha diversity"),
  plotOutput("plot"),
  hr(),
  fluidRow(column(2,
                  selectInput(inputId = "EA",
                              label = "Environment",
                              choices = "Environment A", selected = "Environment A"),
                  selectInput(inputId = "EB",
                              label = "",
                              choices = "Environment B", selected = "Environment B")),
           column(2,numericInput(inputId = "Ca",
                                 label = "Species richness",
                                 value = 1400),
                  numericInput(inputId = "Cb",
                               label = "",
                               value = 1400)),
           column(2,numericInput(inputId = "na1",
                                 label = "Number of reads",
                                 value = 7000),
                  numericInput(inputId = "nb1",
                               label = "",
                               value = 7000)),
           column(2,
                  numericInput(inputId = "na2",
                               label = "Number of reads",
                               value = 7000),
                  numericInput(inputId = "nb2",
                               label = "",
                               value = 7000)
           ),
           column(2,
                  numericInput(inputId = "aa",
                               label = "Shape parameter 1",
                               value = 2),
                  numericInput(inputId = "ba",
                               label = "",
                               value = 1.8)
           ),
           column(2,
                  numericInput(inputId = "ab",
                               label = "Shape parameter 2",
                               value = 2),
                  numericInput(inputId = "bb",
                               label = "",
                               value = 2)
           )),
  hr(),
  h2(paste("Probability of correctly determining truth")),
  fluidRow(
    column(4, numericInput(inputId = "replicates",
                           label = "Replicates",
                           value = 2)),
    column(4, numericInput(inputId = "repeats",
                           label = "Repeats",
                           value = 5)
    )),
  tableOutput("results")
)
